server:
  port: ${PORT:8080}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:http://localhost:9000}
      client:
        registration:
          authserver:
            client-name: Spring Auth Server
            client-id: "default-client"
            client-secret: "default-secret"
            scope:
              - openid
              - email
        provider:
          authserver:
            issuer-uri: ${ISSUER_URI:http://localhost:9000}
  ai:
    mcp:
      server:
        protocol: stateless
        name: appointment-server